=== xenomorpheus/heisenberg/src/test/resources/config.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="config">
		<xs:complexType>
			<xs:all>
				<xs:element name="character">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="pcClass" maxOccurs="unbounded"
								minOccurs="0" type="ctPcClassType" />
							<xs:element name="npcClass" maxOccurs="unbounded"
								minOccurs="0" type="ctNpcClassType" />

							<xs:element name="traits">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="traitGroup" maxOccurs="unbounded"
											minOccurs="0" type="ctTraitGroupType" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="sizes">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="size" type="ctKeywordType"
											maxOccurs="unbounded" minOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="genders">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="gender" type="ctKeywordType"
											maxOccurs="unbounded" minOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="races">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="race" type="ctKeywordType"
											maxOccurs="unbounded" minOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="items">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item" type="ctItemType" maxOccurs="unbounded"
								minOccurs="1">
								<xs:annotation>
									<xs:documentation>Items that may be instantiated
									</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="spriteSheets">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="spriteSheet" type="ctSpriteSheetType"
								maxOccurs="unbounded" minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="skills">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="skill" type="ctKeywordDetailType"
								maxOccurs="unbounded" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Game Skills Unit Test
									</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="recipes">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="recipe" type="ctRecipeType"
								maxOccurs="unbounded" minOccurs="0">
								<xs:annotation>
									<xs:documentation>
										Crafting of Item objects skill entries are
										mentioned by id only. ingredient entries are mentioned by id
										only. Rules for Ingredients in Precedence Order (This will aid
										auto-allocation of Item objects if this process is added) 1.
										Consumed Ingredient objects before non-consumed so
										non-consumed
										aren't counted twice. 2. Most specific Ingredient
										before
										less-specific to help the matching process Game Recipes
										Unit Test Recipes
									</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>

	<!-- complex types -->

	<xs:complexType name="ctItemType">
		<xs:attribute type="xs:string" name="id" />
		<xs:attribute type="xs:int" name="iconOpenId" />
		<xs:attribute type="xs:int" name="iconClosedId" />
		<xs:attribute type="xs:int" name="iconLeafId" />
	</xs:complexType>

	<xs:complexType name="ctSpriteSheetType">
		<xs:attribute type="xs:string" name="id" />
		<xs:attribute type="xs:string" name="filename" />
		<xs:attribute type="xs:byte" name="width" />
		<xs:attribute type="xs:byte" name="height" />
		<xs:attribute type="xs:byte" name="rows" />
		<xs:attribute type="xs:byte" name="columns" />
	</xs:complexType>

	<xs:complexType name="ctPcClassType">
		<xs:sequence>
			<xs:element name="ability" maxOccurs="unbounded"
				minOccurs="0" type="ctAbilityType">
			</xs:element>
		</xs:sequence>
		<xs:attribute type="xs:string" name="id" use="required" />
		<xs:attribute type="xs:byte" name="combatDice" use="required" />
		<xs:attribute type="xs:byte" name="magicDice" use="required" />
		<xs:attribute type="xs:byte" name="stealthDice" use="required" />
		<xs:attribute type="xs:byte" name="generalDice" use="required" />
		<xs:attribute type="xs:byte" name="encumbrance" use="required" />
		<xs:attribute type="xs:byte" name="mana" use="required" />
		<xs:attribute type="xs:byte" name="actionPoint" use="required" />
		<xs:attribute type="xs:byte" name="health" use="required" />
	</xs:complexType>

	<xs:complexType name="ctNpcClassType">
		<xs:attribute type="xs:string" name="id" use="required" />
		<xs:attribute type="xs:byte" name="combatDice" use="required" />
		<xs:attribute type="xs:byte" name="magicDice" use="required" />
		<xs:attribute type="xs:byte" name="stealthDice" use="required" />
		<xs:attribute type="xs:byte" name="generalDice" use="required" />
	</xs:complexType>

	<xs:complexType name="ctKeywordType">
		<xs:attribute type="xs:string" name="id" use="required" />
	</xs:complexType>

	<xs:complexType name="ctKeywordDetailType">
		<xs:attribute type="xs:string" name="id" use="required" />
		<xs:attribute type="xs:string" name="description" use="required" />
	</xs:complexType>

	<xs:complexType name="ctAbilityType">
		<xs:attribute type="xs:string" name="id" use="required" />
		<xs:attribute type="xs:string" name="value" use="required" />
	</xs:complexType>

	<xs:complexType name="ctTraitGroupType">
		<xs:sequence>
			<xs:element name="traitSubGroup" maxOccurs="unbounded"
				minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="traitSet" maxOccurs="unbounded"
							minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="trait" type="ctKeywordType"
										maxOccurs="unbounded" minOccurs="0">
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute type="xs:string" name="id" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute type="xs:string" name="id" use="required" />
	</xs:complexType>

	<xs:complexType name="ctRecipeType">
		<xs:sequence>
			<xs:element name="skill" type="ctKeywordType" minOccurs="0" />
			<xs:element name="requirements" type="ctRequirementType"
				minOccurs="0" />
			<xs:element name="products" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="item" type="ctProductItemType"
							minOccurs="0" />
						<xs:element name="spell" type="ctKeywordType"
							minOccurs="0" />
						<xs:element name="property" type="ctProductPropertyType"
							minOccurs="0" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute type="xs:string" name="id" use="required" />
		<xs:attribute type="xs:string" name="description" use="required" />
		<xs:attribute type="ctRecipeProcessType" name="process"
			use="optional" />
		<xs:attribute type="xs:byte" name="actionPoints" use="optional" />
		<xs:attribute type="xs:byte" name="mana" use="optional" />
	</xs:complexType>

	<xs:complexType name="ctRequirementType">
		<xs:sequence>
			<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="id" type="xs:string" use="required" />
					<xs:attribute name="consumed" type="xs:boolean" use="optional" />
					<xs:attribute name="weightMin" type="xs:byte" use="optional" />
					<xs:attribute name="type" type="xs:string" use="optional" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="ctRecipeProcessType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="createItem1"></xs:enumeration>
			<xs:enumeration value="eat1"></xs:enumeration>
			<!-- Test -->
			<xs:enumeration value="testSpell1"></xs:enumeration>
			<xs:enumeration value="testCreateItem1"></xs:enumeration>
			<xs:enumeration value="testEat1"></xs:enumeration>
			<xs:enumeration value="testDrink1"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="ctEntityPropertyType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="aeration"></xs:enumeration>
			<xs:enumeration value="entertainment"></xs:enumeration>
			<xs:enumeration value="hydration"></xs:enumeration>
			<xs:enumeration value="nourishment"></xs:enumeration>
			<xs:enumeration value="rest"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="ctProductItemType">
		<xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="weightBase" type="xs:float" use="optional" />
	</xs:complexType>

	<xs:complexType name="ctProductPropertyType">
		<xs:attribute name="id" type="xs:string" use="required" />
		<xs:attribute name="propertyName" type="ctEntityPropertyType" use="required" />
		<xs:attribute name="propertyDelta" type="xs:float" use="required" />
	</xs:complexType>

</xs:schema>

=== xenomorpheus/heisenberg/src/test/resources/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd">

	<items>
		<!-- Items that may be instantiated -->
		<item id="Arrow" iconOpenId="23" iconClosedId="23" iconLeafId="23" />
		<item id="Backpack" />
		<item id="Bag" />
		<item id="BagOfHolding" />
		<item id="Box" />
		<item id="Candle" />
		<item id="Cat" />
		<item id="Cloak" iconOpenId="46" iconClosedId="46" iconLeafId="46" />
		<item id="Cookie" />
		<item id="Crossbow" iconOpenId="280" iconClosedId="280"
			iconLeafId="280" />
		<item id="CrossbowBolt" iconOpenId="23" iconClosedId="23"
			iconLeafId="23" />
		<item id="Elf" />
		<item id="FlintAndTinder" />
		<item id="Fungus" />
		<item id="Halfling" />
		<item id="Hand" />
		<item id="Horse" />
		<item id="Human" iconOpenId="126" iconClosedId="126" iconLeafId="126" />
		<item id="HumanoidHead" />
		<item id="Location" />
		<item id="MagicRing" iconOpenId="312" iconClosedId="312"
			iconLeafId="312" />
		<item id="OrbOfLight" />
		<item id="Purse" />
		<item id="Quiver" />
		<item id="Rat" />
		<item id="Ring" iconOpenId="312" iconClosedId="312" iconLeafId="312" />
		<item id="Scabbard" />
		<item id="Shield" iconOpenId="31" iconClosedId="31" iconLeafId="31" />
		<item id="SmallGroundFire" />
		<item id="Sword" />
		<item id="Torch" />
		<item id="Water" />
		<item id="Wood" />
	</items>

	<character>
		<pcClass id="Soldier" combatDice="20" magicDice="4"
			stealthDice="8" generalDice="12" encumbrance="100" mana="0"
			actionPoint="8" health="7">
			<ability id="Dweomer Lore" value="0" />
			<ability id="Mechanisms" value="0" />
			<ability id="Magical Attack" value="0" />
			<ability id="Crafting" value="3/+1" />
			<ability id="Perception" value="4" />
			<ability id="Trickery" value="0" />
			<ability id="Ranged Attack" value="3/+1" />
			<ability id="Enchantment" value="0" />
			<ability id="Advantage Attack" value="2" />
			<ability id="Resistance" value="3" />
			<ability id="Appraisal" value="3/+1" />
			<ability id="Magic Defence" value="2" />
			<ability id="Melee Attack" value="3/+1" />
			<ability id="Combat Defence" value="4/+1" />
			<ability id="Sneak" value="2" />
		</pcClass>
		<pcClass id="Warrior" combatDice="20" magicDice="4"
			stealthDice="12" generalDice="8" actionPoint="8" health="7"
			encumbrance="100" mana="0">
			<ability id="Dweomer Lore" value="0" />
			<ability id="Mechanisms" value="0" />
			<ability id="Magical Attack" value="0" />
			<ability id="Crafting" value="2" />
			<ability id="Perception" value="4" />
			<ability id="Trickery" value="1/+1" />
			<ability id="Ranged Attack" value="3/+1" />
			<ability id="Enchantment" value="0" />
			<ability id="Advantage Attack" value="2" />
			<ability id="Resistance" value="3" />
			<ability id="Appraisal" value="2" />
			<ability id="Magic Defence" value="2" />
			<ability id="Melee Attack" value="4/+1" />
			<ability id="Combat Defence" value="3/+1" />
			<ability id="Sneak" value="3/+1" />
		</pcClass>
		<pcClass id="Paladin" combatDice="20" magicDice="12"
			stealthDice="4" generalDice="8" actionPoint="8" health="6"
			encumbrance="100" mana="3">
			<ability id="Dweomer Lore" value="2" />
			<ability id="Mechanisms" value="0" />
			<ability id="Magical Attack" value="3/+1" />
			<ability id="Crafting" value="1" />
			<ability id="Perception" value="3" />
			<ability id="Trickery" value="0" />
			<ability id="Ranged Attack" value="2/+1" />
			<ability id="Enchantment" value="0" />
			<ability id="Advantage Attack" value="1" />
			<ability id="Resistance" value="3" />
			<ability id="Appraisal" value="1" />
			<ability id="Magic Defence" value="4/+1" />
			<ability id="Melee Attack" value="3/+1" />
			<ability id="Combat Defence" value="4/+1" />
			<ability id="Sneak" value="0" />
		</pcClass>
		<pcClass id="Trickster" combatDice="4" magicDice="12"
			stealthDice="20" generalDice="8" actionPoint="8" health="4"
			encumbrance="100" mana="3">
			<ability id="Dweomer Lore" value="2/+1" />
			<ability id="Mechanisms" value="2" />
			<ability id="Magical Attack" value="3/+1" />
			<ability id="Crafting" value="0" />
			<ability id="Perception" value="2" />
			<ability id="Trickery" value="4/+1" />
			<ability id="Ranged Attack" value="2" />
			<ability id="Enchantment" value="0" />
			<ability id="Advantage Attack" value="0" />
			<ability id="Resistance" value="3" />
			<ability id="Appraisal" value="2" />
			<ability id="Magic Defence" value="2/+1" />
			<ability id="Melee Attack" value="2" />
			<ability id="Combat Defence" value="2" />
			<ability id="Sneak" value="3/+1" />
		</pcClass>
		<pcClass id="Burglar" combatDice="8" magicDice="4"
			stealthDice="20" generalDice="12" encumbrance="100" mana="0"
			actionPoint="8" health="5">
			<ability id="Dweomer Lore" value="0" />
			<ability id="Mechanisms" value="4/+1" />
			<ability id="Magical Attack" value="0" />
			<ability id="Crafting" value="0" />
			<ability id="Perception" value="4/+1" />
			<ability id="Trickery" value="2" />
			<ability id="Ranged Attack" value="3" />
			<ability id="Enchantment" value="0" />
			<ability id="Advantage Attack" value="1" />
			<ability id="Resistance" value="3/+1" />
			<ability id="Appraisal" value="3/+1" />
			<ability id="Magic Defence" value="2" />
			<ability id="Melee Attack" value="3" />
			<ability id="Combat Defence" value="3" />
			<ability id="Sneak" value="3/+1" />
		</pcClass>
		<pcClass id="Assassin" combatDice="12" magicDice="4"
			stealthDice="20" generalDice="8" actionPoint="8" health="5"
			encumbrance="100" mana="0">
			<ability id="Dweomer Lore" value="0" />
			<ability id="Mechanisms" value="3" />
			<ability id="Magical Attack" value="0" />
			<ability id="Crafting" value="0" />
			<ability id="Perception" value="3" />
			<ability id="Trickery" value="2/+1" />
			<ability id="Ranged Attack" value="3/+1" />
			<ability id="Enchantment" value="0" />
			<ability id="Advantage Attack" value="4/+1" />
			<ability id="Resistance" value="3" />
			<ability id="Appraisal" value="1" />
			<ability id="Magic Defence" value="3" />
			<ability id="Melee Attack" value="2/+1" />
			<ability id="Combat Defence" value="3" />
			<ability id="Sneak" value="4/+1" />
		</pcClass>
		<pcClass id="Wizard" combatDice="4" magicDice="20"
			stealthDice="8" generalDice="12" actionPoint="8" health="4"
			encumbrance="100" mana="4">
			<ability id="Dweomer Lore" value="4/+1" />
			<ability id="Mechanisms" value="0" />
			<ability id="Magical Attack" value="4/+1" />
			<ability id="Crafting" value="3/+1" />
			<ability id="Perception" value="3" />
			<ability id="Trickery" value="0" />
			<ability id="Ranged Attack" value="1" />
			<ability id="Enchantment" value="3/+1" />
			<ability id="Advantage Attack" value="0" />
			<ability id="Resistance" value="1" />
			<ability id="Appraisal" value="3" />
			<ability id="Magic Defence" value="4/+1" />
			<ability id="Melee Attack" value="1" />
			<ability id="Combat Defence" value="1" />
			<ability id="Sneak" value="0" />
		</pcClass>
		<pcClass id="Priest" combatDice="12" magicDice="20"
			stealthDice="4" generalDice="8" actionPoint="8" health="4"
			encumbrance="100" mana="4">
			<ability id="Dweomer Lore" value="3" />
			<ability id="Mechanisms" value="0" />
			<ability id="Magical Attack" value="3/+1" />
			<ability id="Crafting" value="1" />
			<ability id="Perception" value="3" />
			<ability id="Trickery" value="1" />
			<ability id="Ranged Attack" value="1" />
			<ability id="Enchantment" value="2/+1" />
			<ability id="Advantage Attack" value="1" />
			<ability id="Resistance" value="2" />
			<ability id="Appraisal" value="2" />
			<ability id="Magic Defence" value="4/+1" />
			<ability id="Melee Attack" value="2/+1" />
			<ability id="Combat Defence" value="1/+1" />
			<ability id="Sneak" value="0" />
		</pcClass>
		<pcClass id="Druid" combatDice="8" magicDice="20" stealthDice="4"
			generalDice="12" actionPoint="8" health="4" encumbrance="100" mana="4">
			<ability id="Dweomer Lore" value="2" />
			<ability id="Mechanisms" value="0" />
			<ability id="Magical Attack" value="3/+1" />
			<ability id="Crafting" value="2/+1" />
			<ability id="Perception" value="4" />
			<ability id="Trickery" value="0" />
			<ability id="Ranged Attack" value="2" />
			<ability id="Enchantment" value="1/+1" />
			<ability id="Advantage Attack" value="1" />
			<ability id="Resistance" value="2" />
			<ability id="Appraisal" value="0" />
			<ability id="Magic Defence" value="4/+1" />
			<ability id="Melee Attack" value="2" />
			<ability id="Combat Defence" value="2" />
			<ability id="Sneak" value="3/+1" />
		</pcClass>
		<pcClass id="Witch" combatDice="8" magicDice="12" stealthDice="12"
			generalDice="12" actionPoint="8" health="4" encumbrance="100" mana="4">
			<ability id="Dweomer Lore" value="2" />
			<ability id="Mechanisms" value="0" />
			<ability id="Magical Attack" value="3/+1" />
			<ability id="Crafting" value="4" />
			<ability id="Perception" value="3" />
			<ability id="Trickery" value="2/+1" />
			<ability id="Ranged Attack" value="2" />
			<ability id="Enchantment" value="1/+1" />
			<ability id="Advantage Attack" value="0" />
			<ability id="Resistance" value="1/+1" />
			<ability id="Appraisal" value="0" />
			<ability id="Magic Defence" value="3/+1" />
			<ability id="Melee Attack" value="2" />
			<ability id="Combat Defence" value="2" />
			<ability id="Sneak" value="3" />
		</pcClass>
		<pcClass id="Hunter" combatDice="12" magicDice="8"
			stealthDice="12" generalDice="12" actionPoint="8" health="6"
			encumbrance="100" mana="1">
			<ability id="Dweomer Lore" value="0" />
			<ability id="Mechanisms" value="0" />
			<ability id="Magical Attack" value="1" />
			<ability id="Crafting" value="3" />
			<ability id="Perception" value="3/+1" />
			<ability id="Trickery" value="0" />
			<ability id="Ranged Attack" value="4/+1" />
			<ability id="Enchantment" value="0" />
